services:
    php:
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 8000:8000
        depends_on:
            - database
        networks:
            - laravel
            
    # webserver:
    #     image: nginx:alpine
    #     container_name: laravel_webserver
    #     working_dir: /var/www
    #     volumes:
    #         - ./:/var/www
    #         - ./docker/nginx/conf.d:/etc/nginx/conf.d
    #     ports:
    #         - "8000:80"
    #     networks:
    #         - laravel

    database:
        image: mysql:8.0
        container_name: laravel_db
        environment:
            MYSQL_USER: "nang"
            MYSQL_PASSWORD: "root" 
            MYSQL_ROOT_PASSWORD: "root" 
            MYSQL_DATABASE: ${DB_DATABASE}
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "8306:3306"
        networks:
            - laravel

networks:
    laravel:

volumes:
    dbdata:
