services:
    app:
        image: php:8.0-fpm
        container_name: laravel_app
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - laravel

    webserver:
        image: nginx:alpine
        container_name: laravel_webserver
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "8000:80"
        networks:
            - laravel

    db:
        image: mysql:5.7
        container_name: laravel_db
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: password # Set a root password for MySQL
            MYSQL_DATABASE: metanarasi
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "8306:3306"
        networks:
            - laravel

networks:
    laravel:

volumes:
    dbdata:
